#!/bin/bash
. /home/echbayols.conf

cd ~

if [ ! -d /etc/echbay/.tmp ]; then
mkdir -p /etc/echbay/.tmp
fi


checkketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://raw.githubusercontent.com/itvn9online/openlitespeed-autoinstall/main/version" )
#echo $checkketnoi
if [[ "$checkketnoi" == "000" ]]; then
clear
echo "========================================================================="
echo "ERROR connect to update server"
echo "-------------------------------------------------------------------------"
echo "Please retry!"
echbay
exit
fi

#
rm -rf /etc/echbay/.tmp/echbay-update-*


wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/openlitespeed-autoinstall/main/echbay-update-run -O /etc/echbay/.tmp/echbay-update-run
chmod +x /etc/echbay/.tmp/echbay-update-run
bash /etc/echbay/.tmp/echbay-update-run


