#!/bin/bash
. /home/echbayols.conf

# copy code tu file install sang
cd ~
wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/openlitespeed-autoinstall/main/menu/git-clone
chmod +x /root/git-clone
bash /root/git-clone


# BEGIN update ECHBAY-OLS main
#rm -rf /etc/motd
yes | cp -rf /opt/echbayols/motd /etc/motd

yes | cp -rf /opt/echbayols/calc /bin/calc && chmod +x /bin/calc

yes | cp -rf /opt/echbayols/echbay /bin/echbay && chmod +x /bin/echbay
# BEGIN update ECHBAY-OLS main


# BEGIN update ECHBAY-OLS menu
rm -rf /etc/echbay/menu/*
yes | cp -rf /opt/echbayols/menu/. /etc/echbay/menu/

# Chmod 755 Menu
/opt/echbayols/menu/chmod-755-menu
# END update ECHBAY-OLS menu


# confirm done update
yes | cp -rf /opt/echbayols/version /etc/echbay/echbay.version


#rm -rf /opt/echbayols/*
#rm -rf /opt/echbayols
sleep 1


/etc/echbay/menu/update-upgrade-service-menu

#exit
