#!/bin/sh

# https://github.com/litespeedtech/ls-cloud-image/tree/master/Setup

cd ~
if [ -d /opt/echbayols ]; then
rm -rf /opt/echbayols/*
rm -rf /opt/echbayols
sleep 5
fi

sudo yum -y install wget

#
cd ~
wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/openlitespeed-autoinstall/main/menu/git-clone
chmod +x ~/git-clone
bash ~/git-clone

cd /opt/echbayols
chmod +x setup
bash setup
