#!/bin/sh

DATABASE_PASS=$(cat /tmp/passrootmysql)
if [ -f /tmp/echbayols.conf ]; then
	. /tmp/echbayols.conf
	DATABASE_PASS=$passrootmysql
mysqladmin -u root password "$DATABASE_PASS"
# Make sure that NOBODY can access the server without a password
mysql -u root -p"$DATABASE_PASS" -e "UPDATE mysql.user SET Password=PASSWORD('$DATABASE_PASS') WHERE User='root'"
# Kill the anonymous users
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User=''"
# Kill off the demo database
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
# Make our changes take effect
mysql -u root -p"$DATABASE_PASS" -e "FLUSH PRIVILEGES"

sed -i '/mariadbpass=/d' /home/echbayols.conf
cat >> "/home/echbayols.conf" <<END
mariadbpass="$DATABASE_PASS"
END

#########
#rm -rf /tmp/passrootmysql
yes | cp -rf /bin/mysql_secure_installation /tmp/mysql_secure_installation_del
fi

yes | cp -rf /opt/echbayols/mysql_secure_installation_bak /bin/mysql_secure_installation && chmod +x /bin/mysql_secure_installation
#########
