#!/bin/bash

echo "Enter new domain name for add new (Without www):"
read DOMAIN

DOMAIN=`echo $DOMAIN | tr '[A-Z]' '[a-z]'`
if [ "$DOMAIN" == "" ]; then
clear
echo "========================================================================="
echo "Please enter your domain and retry!"
/etc/echbay/menu/scripts/lscreate
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$DOMAIN" =~ $kiemtradomain3 ]]; then
	DOMAIN=`echo $DOMAIN | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$DOMAIN Domain format warning! you want continue? (y/N):"
read tiep_tuc_add_domain
if [ ! "$tiep_tuc_add_domain" = "y" ]; then
/etc/echbay/menu/scripts/lscreate
exit
fi
fi

echo "FTP Username (empty for skip create FTP account):"
read USERNAME
if [ ! "$USERNAME" = "" ]; then
echo "FTP Password:"
read PASSWORD
fi

HOMEDIR="/home/$DOMAIN"
SERVERROOT="/usr/local/lsws"
DOMAINCONF="$SERVERROOT/conf/templates/$DOMAIN.conf"

# Create directory
mkdir $HOMEDIR
mkdir $HOMEDIR/{html,logs}
mkdir $SERVERROOT/conf/vhosts/$DOMAIN
mkdir $SERVERROOT/conf/cert/$DOMAIN

# Create file
touch $HOMEDIR/html/.htaccess
touch /$HOMEDIR/logs/{error.log,access.log}
cat << EOT > $HOMEDIR/html/index.php
<?php
echo "Its Works!";
?>
EOT

# Modify LS config file
cp $SERVERROOT/conf/templates/incl.conf $SERVERROOT/conf/templates/$DOMAIN.conf
cp $SERVERROOT/conf/templates/vhconf.conf $SERVERROOT/conf/vhosts/$DOMAIN/vhconf.conf
sed -i "s/##DOMAIN##/$DOMAIN/g" $SERVERROOT/conf/templates/$DOMAIN.conf
sed -i "s/##DOMAIN##/$DOMAIN/g" $SERVERROOT/conf/vhosts/$DOMAIN/vhconf.conf
sed -i "/echbayols.demo[[:space:]][*]/a \  map                     $DOMAIN $DOMAIN" $SERVERROOT/conf/httpd_config.conf
sed -i "s/virtualhost[[:space:]]echbayols.demo[[:space:]]{/cat \/usr\/local\/lsws\/conf\/templates\/$DOMAIN.conf/e" $SERVERROOT/conf/httpd_config.conf
rm -f $DOMAINCONF

# Generate Cert
openssl genrsa -out $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key 2048
openssl rsa -in $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key -out $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key
openssl req -sha256 -new -key $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key -out $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.csr -subj "/CN=$DOMAIN"
openssl x509 -req -sha256 -days 365 -in $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.csr -signkey $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key -out $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.crt

# Create FTP User
if [ ! "$USERNAME" = "" ]; then
useradd $USERNAME -d /home/$DOMAIN -p $(echo $PASSWORD | openssl passwd -1 -stdin) -M
fi

# Fix Permission
if [ ! "$USERNAME" = "" ]; then
chown -R $USERNAME:$USERNAME $HOMEDIR/html/
fi
chown -R lsadm:lsadm $SERVERROOT/conf/cert/
chown -R lsadm:lsadm $SERVERROOT/conf/vhosts/
chown -R lsadm:lsadm $SERVERROOT/conf/templates/

# Reload
/usr/local/lsws/bin/lswsctrl reload
echo -e $DOMAIN:$HOMEDIR >> $SERVERROOT/domain
echo =================================================
echo Done!
echo Your vhost is ready
echo "Domain       : $DOMAIN"
echo "Homedir      : $HOMEDIR"
if [ ! "$USERNAME" = "" ]; then
echo "FTP User     : $USERNAME"
echo "FTP Password : $PASSWORD"
fi
echo =================================================

#/etc/echbay/menu/them-website-menu
/bin/echbay

