#!/bin/bash

. /home/echbayols.conf

/etc/echbay/menu/scripts/lslist

echo "========================================================================="
if [ ! "$1" = "" ]; then
	DOMAIN=$1
else
	echo "Enter new domain name for add new (Without www):"
	read DOMAIN
fi

DOMAIN=`echo $DOMAIN | tr '[A-Z]' '[a-z]'`
if [ "$DOMAIN" == "0" ] || [ "$DOMAIN" == "" ]; then
clear
echo "Cancel add domain"
/bin/echbay
fi

#if [ "$DOMAIN" == "" ]; then
#clear
#echo "========================================================================="
#echo "Please enter your domain and retry!"
#/etc/echbay/menu/scripts/lscreate
#exit
#fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$DOMAIN" =~ $kiemtradomain3 ]]; then
	DOMAIN=`echo $DOMAIN | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$DOMAIN Domain format warning! you want continue? (y/N):"
read tiep_tuc_add_domain
if [ ! "$tiep_tuc_add_domain" = "y" ]; then
/etc/echbay/menu/scripts/lscreate
exit
fi
fi

if [ ! "$2" = "" ]; then
	USERNAME=$2
else
	echo "FTP Username (empty for skip create FTP account):"
	read USERNAME
fi

if [ ! "$USERNAME" = "" ]; then
	if [ ! "$3" = "" ]; then
		PASSWORD=$3
	else
		echo "FTP Password:"
		read PASSWORD
	fi
fi

#echo $DOMAIN
#echo $USERNAME
#echo $PASSWORD
#echo "TEST TEST TEST TEST TEST TEST..." ; exit

#
if [ ! "$USERNAME" = "" ] && [ ! -f /etc/proftpd.conf ]; then
HOMEDIR="/home/$USERNAME"
else
HOMEDIR="/home/$DOMAIN"
fi
#echo $HOMEDIR ; exit
SERVERROOT="/usr/local/lsws"
DOMAINCONF="$SERVERROOT/conf/templates/$DOMAIN.conf"

# Create directory
mkdir -p $HOMEDIR
mkdir -p $HOMEDIR/{html,logs}
mkdir -p $SERVERROOT/conf/vhosts/$DOMAIN
mkdir -p $SERVERROOT/conf/cert/$DOMAIN

#
mkdir -p $HOMEDIR/html/.well-known/acme-challenge
mkdir -p $HOMEDIR/html/.well-known/pki-validation
mkdir -p $HOMEDIR/html/.well-known

# tao file theo ten mien duoc add
echo $(date) > "$HOMEDIR/$DOMAIN.txt"

#echo "TEST TEST TEST TEST TEST TEST..." ; exit

# Create file
#touch $HOMEDIR/html/.htaccess
yes | cp -rf /etc/echbay/htaccess.txt $HOMEDIR/html/.htaccess
touch /$HOMEDIR/logs/{error.log,access.log}
if [ -f /opt/echbayols/conf/index.zip ]; then
yes | cp -rf /opt/echbayols/conf/index.zip $HOMEDIR/html/index.php
else
cat << EOT > $HOMEDIR/html/index.php
<?php
echo "Webcome to EchBay OpenLiteSpeed Hosting!";
echo phpversion();
echo __FILE__ . ':' . __LINE__;
?>
EOT
fi

# Modify LS config file
yes | cp -rf $SERVERROOT/conf/templates/incl.conf $SERVERROOT/conf/templates/$DOMAIN.conf
yes | cp -rf $SERVERROOT/conf/templates/vhconf.conf $SERVERROOT/conf/vhosts/$DOMAIN/vhconf.conf
sed -i "s/##DOMAIN##/$DOMAIN/g" $SERVERROOT/conf/templates/$DOMAIN.conf
sed -i "s/##DOMAIN##/$DOMAIN/g" $SERVERROOT/conf/vhosts/$DOMAIN/vhconf.conf
sed -i "/echbayols.demo[[:space:]][*]/a \  map                     $DOMAIN $DOMAIN" $SERVERROOT/conf/httpd_config.conf
sed -i "s/virtualhost[[:space:]]echbayols.demo[[:space:]]{/cat \/usr\/local\/lsws\/conf\/templates\/$DOMAIN.conf/e" $SERVERROOT/conf/httpd_config.conf
rm -f $DOMAINCONF

# Generate Cert
openssl genrsa -out $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key 2048
openssl rsa -in $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key -out $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key
openssl req -sha256 -new -key $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key -out $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.csr -subj "/CN=$DOMAIN"
openssl x509 -req -sha256 -days 365 -in $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.csr -signkey $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.key -out $SERVERROOT/conf/cert/$DOMAIN/$DOMAIN.crt

# Create FTP User -> PureFTPD
add_ftp_user_pure(){

user=$USERNAME
passwd=$PASSWORD
udir="/home/$USERNAME"
dm_str_login="sbin/nologin"
#ma_hoa_public_user_dir="8705079b8deaa02006a160f0342f05b0"
#file_name_to_index_download="index"
#domain="wp25882.s146.echbay.com"
#dir_for_nginx_domain="/etc/nginx"
#dm_id="25882"
#dir_for_nginx_centmin_domain="/usr/local/nginx/conf"
#act="process"

#
id -u $user
if [ $? -eq 0 ]; then
echo "user_exist"
else
#echo "user_does_not_exist"
/usr/sbin/useradd $user
/usr/sbin/usermod -d $udir $user
echo $user:$passwd | /usr/sbin/chpasswd
fi
/usr/sbin/usermod -s /$dm_str_login $user
if [ -f /etc/pure-ftpd/pure-ftpd.conf ]; then
if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi
if [ "$(pure-pw list | grep $udir)" == "" ]; then
( echo ${passwd} ; echo ${passwd} ) | pure-pw useradd $user -u nginx -g nginx -d $udir -m
pure-pw mkdb
pure-pw mkdb
fi
fi

}

# Create FTP User -> ProFTPD
if [ ! "$USERNAME" = "" ]; then

if [ -f /etc/pure-ftpd/pure-ftpd.conf ]; then
add_ftp_user_pure
elif [ -f /etc/proftpd.conf ]; then
#/usr/sbin/useradd $USERNAME -d /home/$DOMAIN -p $(echo $PASSWORD | openssl passwd -1 -stdin) -M
/usr/sbin/useradd $USERNAME -d $HOMEDIR -p $(echo $PASSWORD | openssl passwd -1 -stdin) -M
fi

fi

# Fix Permission
if [ ! "$USERNAME" = "" ]; then
chown -R $USERNAME:$USERNAME $HOMEDIR/html/
fi
chown -R lsadm:lsadm $SERVERROOT/conf/cert/
chown -R lsadm:lsadm $SERVERROOT/conf/vhosts/
chown -R lsadm:lsadm $SERVERROOT/conf/templates/

# Reload
/usr/local/lsws/bin/lswsctrl reload
echo -e $DOMAIN:$HOMEDIR >> $SERVERROOT/domain
echo =================================================
echo Done!
echo Your vhost is ready
echo "Domain       : $DOMAIN"
echo "Homedir      : $HOMEDIR"
if [ ! "$USERNAME" = "" ]; then
echo "FTP User     : $USERNAME"
echo "FTP Password : $PASSWORD"
fi
echo =================================================

#/etc/echbay/menu/them-website-menu
/bin/echbay

