#!/bin/bash

. /home/echbayols.conf

echo "========================================================================="
echo "Current domain list on server:"
for d in /home/*
do
	if [ -d $d ]; then
#		d=$(($d | cut -c7-100))
		if [ ! "$d" = "/home/$mainsite" ]; then
#			echo $d
			echo $d | cut -c7-100
		fi
	fi
done
