#!/bin/sh

curTime=$(date +%d)
#echo "curTime: "$curTime


if [ ! -f /tmp/echbayols.newversion ]; then
touch -a -m -t 201602180130.09 /tmp/echbayols.newversion  
fi

fileTime2=$(date -r /tmp/echbayols.newversion +%d)
#echo "fileTime2: "$fileTime2

if [ ! "$fileTime2" == "$curTime" ]; then
rm -rf /tmp/echbayols.newversion
wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/openlitespeed-autoinstall/main/version -O /tmp/echbayols.newversion
touch /tmp/echbayols.newversion
LOCALVER=`cat /etc/echbay/echbayols.version`
checksize=$(du -sb /tmp/echbayols.newversion | awk 'NR==1 {print $1}')
###
	if [ $checksize -gt 2 ]; then
	REMOVER=`cat /tmp/echbayols.newversion`
	cat >> "/tmp/echbay_check_echbay_version" <<END
		if [ ! "$LOCALVER" == "$REMOVER" ]; then
			echo "========================================================================="
			echo "Update for ECHBAY-OLS found !  "
			echo "-------------------------------------------------------------------------"
			echo "Your Version: $LOCALVER   |   Newest version: $REMOVER"
			echo "-------------------------------------------------------------------------"
			echo "How to update: ECHBAY-OLS menu => Update System => Update ECHBAY-OLS "
			
		fi
END
	chmod +x /tmp/echbay_check_echbay_version
	/tmp/echbay_check_echbay_version
	rm -rf /tmp/echbay_check_echbay_version
	fi
fi



