#!/bin/sh
. /home/echbayols.conf

if [ ! -f /var/spool/cron/root ]; then
/etc/echbay/menu/crontab/xoa-het-cronjob
exit
fi

if [ "$(grep "auto-start-mysql" /var/spool/cron/root | awk '{print $6}')" == "auto-start-mysql" ]; then
/etc/echbay/menu/crontab/xoa-het-cronjob-but-auto-start-mariadb
exit
fi
if [ "$(grep "auto-start-mysql" /var/spool/cron/root | awk '{print $6}')" == "" ]; then
/etc/echbay/menu/crontab/xoa-het-cronjob
exit
fi
clear
echo "we can find cronjob for you"
/etc/echbay/menu/crontab/cronjob-menu
exit
fi
