#!/bin/bash
. /home/echbayols.conf

if [ "$(crontab -l | awk 'NR==1 {print $1}')" == "" ]; then
clear
echo "========================================================================= "
echo "Ban chua tao crontab tren VPS !"
/etc/echbay/menu/crontab/cronjob-menu
exit
fi
clear
echo "========================================================================= "
echo "Danh sach Crontab dang chay:"
echo "-------------------------------------------------------------------------"
crontab -l
/etc/echbay/menu/crontab/cronjob-menu
exit
fi
