#!/bin/bash
. /home/echbayols.conf

if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
clear
echo "========================================================================= "
echo "FTP Server chua duoc cai dat "
echo "-------------------------------------------------------------------------"
echo "Ban phai cai dat chuc nang Setup FTP server truoc"
exit
fi

echo "========================================================================="
echo "Su dung chuc nang nay de tao FTP user cho  website"
echo "-------------------------------------------------------------------------"
if [ ! "$1" = "" ]; then
	website=$1
else
	echo -n "Nhap website ban muon them FTP user [ENTER]: " 
	read website
fi

if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ban nhap sai, vui long nhap lai!"
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website co le khong phai la domain !"
echo "-------------------------------------------------------------------------"
echo "Ban vui long nhap lai  !"
exit
fi

if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi

if [ ! "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Ban da tao tai khoan FTP cho $website" 
echo "-------------------------------------------------------------------------"
echo "Thong tin tai khoan FTP:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $(grep "/home/$website/" /etc/echbay/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/echbay/FTP-Account.info | awk 'NR==1 {print $10}')"
fi


echo "-------------------------------------------------------------------------"
echo "Tim thay $website tren he thong"
echo "-------------------------------------------------------------------------"
echo "$website chua tao tai khoan FTP"
echo "-------------------------------------------------------------------------"
echo "ECHBAY se tao tai khoan FTP cho $website ngay bay gio"
echo "-------------------------------------------------------------------------"
echo "Please wait..."; sleep 6


echo "$website" > /tmp/echbayftp.txt
sed -i '  s/\./_/g' /tmp/echbayftp.txt
sed -i 's/\-/_/g' /tmp/echbayftp.txt
username=`cat /tmp/echbayftp.txt | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | cut -c1-30`
password=`date |md5sum |cut -c '3-23'`
#useradd -m -d /home/$website -g nginx -p $password $username
#usermod -aG nginx $username
#chmod g+rxw /home/$website
( echo ${password} ; echo ${password} ) | pure-pw useradd $username -u nginx -g nginx -d /home/$website -m 
pure-pw mkdb
rm -rf /tmp/echbayftp.txt;
pure-pw mkdb
if [ ! -f /etc/echbay/FTP-Account.info ]; then
echo "=========================================================================" > /etc/echbay/FTP-Account.info
echo "Please Do Not Delete This File " >> /etc/echbay/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/echbay/FTP-Account.info
echo "If you delete this file, ECHBAY will not run !" >> /etc/echbay/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/echbay/FTP-Account.info
echo "All FTP User for all domain on VPS list below:" >> /etc/echbay/FTP-Account.info
echo "=========================================================================" >> /etc/echbay/FTP-Account.info
echo "" >> /etc/echbay/FTP-Account.info
fi
################
echo "FTP Account for $website | Username: $username | Password: $password | dd /home/$website/ " >> /etc/echbay/FTP-Account.info
clear
echo "=========================================================================" 
echo "Tao tai khoan FTP cho $website thanh cong"
echo "-------------------------------------------------------------------------"
echo "Thong tin login:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $username | Password: $password"
