#!/bin/bash

printf "=========================================================================\n"
printf "                ECHBAY-OLS - Quan Ly VPS/Server by EchBay.com \n"
printf "=========================================================================\n"
printf "                   Chuc nang nay khong ho tro VPS OpenVZ\n"
printf "=========================================================================\n"
