#!/bin/bash
if [ ! -f /etc/cron.d/echbay.code.cron ]; then
touch /etc/cron.d/echbay.code.cron
fi
prompt="Lua chon cua ban (0-Thoat):"
#options=( "Them Website" "Them Park & Redirect Domain" "Them website + Wordpress (Auto Setup)" "Them website + Forum Code (Auto Setup)" "Them Website + Opencart (Auto Setup)" "Them website + Wordpress (Download Code)" "Them Website + Joomla (Download Code)" "Them Website + Drupal (Download Code)" "List Website Tren Server" "Thoat")
options=( "Them Website" "Let's Encrypt Certificate" )

/etc/echbay/menu/text-header
printf "                          Them Website Vao Server\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

case "$REPLY" in

1) /etc/echbay/menu/scripts/lscreate;;
2) /etc/echbay/menu/scripts/certbot;;
#1) /etc/echbay/menu/echbay-them-website;;
#2) /etc/echbay/menu/echbay-them-redirect-park-domain-menu;;
#3) /etc/echbay/menu/echbay-them-website-auto-setup-wordpress-menu;;
#4) /etc/echbay/menu/echbay-them-website-forum-code-menu;;
#5) /etc/echbay/menu/echbay-them-website-auto-setup-opencart-menu;;
#6) /etc/echbay/menu/echbay-them-website-wp;;
#7) /etc/echbay/menu/echbay-them-website-joomla;;
#8) /etc/echbay/menu/echbay-them-website-drupal;;
#9) /etc/echbay/menu/echbay-list-website-tren-vps;; 
#10) clear && echbay;;
0) clear && echbay;;
*) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

esac

done



