#!/bin/sh
. /home/echbayols.conf
/etc/echbay/menu/vps-info-befor
clear
printf "=========================================================================\n"
printf "             ECHBAY-OLS - Quan Ly VPS/Server by WebGiaRe.org \n"
printf "=========================================================================\n"
printf "                            Server Status \n"
printf "=========================================================================\n"
echo "IP: $serverip - Disc Free: $(calc $(df $PWD | awk '/[0-9]%/{print $(NF-2)}')/1024) MB"
echo "OS: "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))
echo "-------------------------------------------------------------------------"
if [ -f /etc/csf/csf.deny ]; then
if [ "$(cat /etc/csf/csf.deny | awk 'NR==2 {print $2}')" == "Copyright" ]; then
rm -rf /etc/csf/csf.deny
cat > "/etc/csf/csf.deny" <<END
END
fi
fi

if [ -f /root/.bash_profile ]; then
if [ "$(grep timeloginechbayolscheck /root/.bash_profile)" == "" ]; then
echo "-------------------------------------------------------------------------"
echo "eMail thong bao Login: TAT"
else
echo "-------------------------------------------------------------------------"
echo "eMail thong bao Login: BAT | eMail: $(grep "mail -s" /root/.bash_profile  | awk 'NR==1 {print $NF}')"
fi
fi

rm -rf /tmp/*echbay*
rm -rf /tmp/*check*

echo "========================================================================="
echo "Connections to:  80 Port: $(netstat -n | grep :80 |wc -l) | 443 Port: $(netstat -n | grep :443 |wc -l)"
echo "========================================================================="
echo "Server Uptime: $(uptime | awk '{print $3,$4}' | sed 's/,/ /g') - CPU Load Average: $(uptime | awk '{print $(NF-2),$(NF-1),$NF}' | sed 's/,/ /g')"
echo "RAM: $( free -m | grep Mem | awk '{print $2}') MB - Free: $( free -m | grep Mem | awk '{print $4}') MB - Cached: $( free -m | grep Mem | awk '{print $7}') MB || Free buffers: $(free -m | grep - | awk '{print $4}') MB"
echo "Swap: $(free -m | grep Swap | awk '{print $2}') MB - Swap free: $(free -m | grep Swap | awk '{print $4}') MB"
printf "=========================================================================\n"
read -p "Nhan [Enter] de quay tro lai ECHBAY-OLS menu ..."
clear
echbay
exit
fi

