#!/bin/bash

# Random Password Generator
ROOTSQLPWD=`date |md5sum |cut -c '1-15'`
PMABLOWFISH=`date |md5sum |cut -c '1-32'`;

# Define short code
GITRAW=https://raw.githubusercontent.com/tujuhion/openlitespeed-centos-autoinstall/master
LSWSDIR=/usr/local/lsws


current_os_version=$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))
if [ "$current_os_version" == "7" ]; then
el_version=$current_os_version
else
el_version="8"
fi

# Update
yum -y install epel-release
yum -y install wget certbot openssl
#wget -O /etc/yum.repos.d/MariaDB.repo $GITRAW/repo/MariaDB.repo
cat > "/etc/yum.repos.d/mariadb.repo" <<END
# MariaDB $phienbanmariadb CentOS repository list 
# http://downloads.mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/$phienbanmariadb/centos$el_version-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
END
rpm -ivh http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el${el_version}.noarch.rpm
yum -y update

# Install Proftpd
yum -y install proftpd
sed -i "s/ProFTPD server/$HOSTNAME/g" /etc/proftpd.conf

#Install Openlitespeed & MariaDB
mkdir /home/echbayols.demo
mkdir /home/echbayols.demo/html
mkdir /home/echbayols.demo/logs
yum -y install openlitespeed
yum -y install MariaDB-server MariaDB-client

# Install PHP 72
#yum -y install lsphp72 lsphp72-common lsphp72-mysqlnd lsphp72-process lsphp72-gd lsphp72-mbstring lsphp72-mcrypt lsphp72-opcache lsphp72-bcmath lsphp72-pdo lsphp72-xml lsphp72-json lsphp72-zip lsphp72-xmlrpc lsphp72-pecl-mcrypt
install_multi_PHP_version () {
	if [ ! -d /usr/local/lsws/lsphp${1} ]; then
		sudo yum -y install lsphp${1} lsphp${1}-common lsphp${1}-mysqlnd lsphp${1}-process lsphp${1}-gd lsphp${1}-mbstring lsphp${1}-mcrypt lsphp${1}-opcache lsphp${1}-bcmath lsphp${1}-pdo lsphp${1}-xml lsphp${1}-json lsphp${1}-zip lsphp${1}-xmlrpc lsphp${1}-pecl-mcrypt
#		sudo yum -y install lsphp${1} lsphp${1}-mysqlnd lsphp${1}-common lsphp${1}-gd lsphp${1}-pdo lsphp${1}-process lsphp${1}-mbstring lsphp${1}-mcrypt lsphp${1}-opcache lsphp${1}-bcmath lsphp${1}-xml
	fi
}
#install_multi_PHP_version "71"
install_multi_PHP_version "72"
#install_multi_PHP_version "73"
#install_multi_PHP_version "74"

#Setting Up
touch $LSWSDIR/domain
mv -f $LSWSDIR/conf/vhosts/Example/ $LSWSDIR/conf/vhosts/echbayols.demo/
rm -f $LSWSDIR/conf/vhosts/echbayols.demo/vhconf.conf
rm -f $LSWSDIR/conf/httpd_config.conf
rm -f $LSWSDIR/admin/conf/admin_config.conf
wget -O $LSWSDIR/conf/vhosts/echbayols.demo/vhconf.conf $GITRAW/conf/vhconf.conf
wget -O $LSWSDIR/conf/httpd_config.conf $GITRAW/conf/httpd_config.conf
wget -O $LSWSDIR/admin/conf/admin_config.conf $GITRAW/conf/admin_config.conf
chown lsadm:lsadm $LSWSDIR/conf/vhosts/echbayols.demo/vhconf.conf
chown lsadm:lsadm $LSWSDIR/conf/httpd_config.conf
chown lsadm:lsadm $LSWSDIR/admin/conf/admin_config.conf

# Copy Script
mkdir /scripts
wget -O /scripts/lscreate $GITRAW/scripts/lscreate
wget -O /scripts/lsremove $GITRAW/scripts/lsremove
wget -O /scripts/certbot $GITRAW/scripts/certbot
wget -O /scripts/createdb $GITRAW/scripts/createdb
wget -O /usr/bin/lsws $GITRAW/scripts/lsws
chmod +x /usr/bin/lsws
chmod +x /scripts/*

#Copy Templates
wget -O $LSWSDIR/conf/templates/incl.conf $GITRAW/templates/incl.conf
wget -O $LSWSDIR/conf/templates/vhconf.conf $GITRAW/templates/vhconf.conf

# Create Content in Homedir and logs
touch /home/echbayols.demo/html/.htaccess
touch /home/echbayols.demo/logs/{error.log,access.log}
cat << EOT > /home/echbayols.demo/html/index.php
<?php
echo "Its Works!";
?>
EOT
chown -R nobody:nobody /home/echbayols.demo/html/

# Installing PHPMYAdmin
mkdir $LSWSDIR/pma
mkdir $LSWSDIR/pma/{html,logs}
mkdir $LSWSDIR/conf/vhosts/pma
mkdir $LSWSDIR/conf/cert/pma
touch $LSWSDIR/pma/logs/error.log
touch $LSWSDIR/pma/logs/access.log
wget -O $LSWSDIR/conf/vhosts/pma/vhconf.conf $GITRAW/conf/pma_vhconf.conf
wget --no-check-certificate -O $LSWSDIR/pma/html/pma.tar.gz https://files.phpmyadmin.net/phpMyAdmin/4.8.2/phpMyAdmin-4.8.2-english.tar.gz
cd $LSWSDIR/pma/html/
tar -xzvf pma.tar.gz
mv phpMyAdmin-4.8.2-english/* ./

#wget -O config.inc.php $GITRAW/conf/config.inc.php
#sed -i "s/#BLOWFISH#/$PMABLOWFISH/g" config.inc.php
sed -e "s|cfg\['blowfish_secret'\] = ''|cfg['blowfish_secret'] = '$PMABLOWFISH'|" config.sample.inc.php > config.inc.php

mkdir tmp
rm -f pma.tar.gz && rm -rf phpMyAdmin-4.8.2-english
cd /
chown -R lsadm:lsadm $LSWSDIR/pma/

# Generate cerificare for PMA
openssl genrsa -out $LSWSDIR/conf/cert/pma/pma.key 2048
openssl rsa -in $LSWSDIR/conf/cert/pma/pma.key -out $LSWSDIR/conf/cert/pma/pma.key
openssl req -sha256 -new -key $LSWSDIR/conf/cert/pma/pma.key -out $LSWSDIR/conf/cert/pma/pma.csr -subj "/CN=localhost"
openssl x509 -req -sha256 -days 365 -in $LSWSDIR/conf/cert/pma/pma.csr -signkey $LSWSDIR/conf/cert/pma/pma.key -out $LSWSDIR/conf/cert/pma/pma.crt

# Open port Needed in Firewall
firewall-cmd --zone=public --permanent --add-port=21/tcp
firewall-cmd --zone=public --permanent --add-port=80/tcp
firewall-cmd --zone=public --permanent --add-port=443/tcp
firewall-cmd --zone=public --permanent --add-port=7080/tcp
firewall-cmd --zone=public --permanent --add-port=8090/tcp
firewall-cmd --reload

# Generate SSL for Webadmin
mkdir $LSWSDIR/conf/cert/admin
openssl genrsa -out $LSWSDIR/conf/cert/admin/admin.key 2048
openssl rsa -in $LSWSDIR/conf/cert/admin/admin.key -out $LSWSDIR/conf/cert/admin/admin.key
openssl req -sha256 -new -key $LSWSDIR/conf/cert/admin/admin.key -out $LSWSDIR/conf/cert/admin/admin.csr -subj "/CN=localhost"
openssl x509 -req -sha256 -days 365 -in $LSWSDIR/conf/cert/admin/admin.csr -signkey $LSWSDIR/conf/cert/admin/admin.key -out $LSWSDIR/conf/cert/admin/admin.crt

#Setting MySQL
systemctl start mariadb && systemctl start proftpd && $LSWSDIR/bin/lswsctrl start
mysql -uroot -v -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
mysql -uroot -v -e "DROP DATABASE test;"
mysql -uroot -v -e "DELETE FROM mysql.user WHERE User='';"
mysql -uroot -v -e "use mysql;update user set Password=PASSWORD('$ROOTSQLPWD') where user='root'; flush privileges;"

# Save Password root MariaDB
cat << EOT > /root/.MariaDB
$ROOTSQLPWD
EOT

# Create PHP symlink
ln -s /usr/local/lsws/lsphp72/bin/lsphp /usr/bin/php

systemctl enable proftpd
systemctl enable mariadb
